export const labelThMap: Record<string, string> = {
  "Akabare Khursani": "พริกขี้หนู",
  Apple: "แอปเปิ้ล",
  Artichoke: "อาร์ติโช้ค",
  "Ash Gourd -Kubhindo-": "ฟักทอง",
  "Asparagus -Kurilo-": "หน่อไม้ฝรั่ง",
  Avocado: "อะโวคาโด",
  Bacon: "เบคอน",
  "Bamboo Shoots -Tama-": "หน่อไม้",
  Banana: "กล้วย",
  Beans: "ถั่ว",
  "Beaten Rice -Chiura-": "ข้าวแตง",
  Beef: "เนื้อวัว",
  Beetroot: "บีทรูท",
  "Bethu ko Saag": "ผักใบเขียว",
  "Bitter Gourd": "มะระขี้นก",
  "Black Lentils": "ถั่วดำ",
  "Black beans": "ถั่วดำ",
  "Bottle Gourd -Lauka-": "ขวดน้ำ",
  Bread: "ขนมปัง",
  Brinjal: "มะเขือยาว",
  "Broad Beans -Bakullo-": "ถั่วลันเตา",
  Broccoli: "บร็อคโคลี่",
  "Buff Meat": "เนื้อควาย",
  Butter: "เนย",
  Cabbage: "กะหล่ำปลี",
  Capsicum: "พริกหยวก",
  Carrot: "แครอท",
  "Cassava -Ghar Tarul-": "มันสำปะหลัง",
  Cauliflower: "กะหล่ำดอก",
  "Chayote-iskus-": "ฟักแม้ว",
  Cheese: "ชีส",
  Chicken: "ไก่",
  "Chicken Gizzards": "กึ๋นไก่",
  Chickpeas: "ถั่วลูกไก่",
  "Chili Pepper -Khursani-": "พริก",
  "Chili Powder": "พริกป่น",
  "Chowmein Noodles": "บะหมี่",
  Cinnamon: "อบเชย",
  "Coriander -Dhaniya-": "ผักชี",
  Corn: "ข้าวโพด",
  Cornflakec: "คอร์นเฟลก",
  "Crab Meat": "เนื้อปู",
  Cucumber: "แตงกวา",
  Egg: "ไข่ไก่",
  "Farsi ko Munta": "มะเขือเทศป่า",
  "Fiddlehead Ferns -Niguro-": "กะหล่ำน้ำ",
  Fish: "ปลา",
  "Garden Peas": "ถั่วลันเตา",
  "Garden cress-Chamsur ko saag-": "ผักกาด",
  Garlic: "กระเทียม",
  Ginger: "ขิง",
  "Green Brinjal": "มะเขือเขียว",
  "Green Lentils": "ถั่วเขียว",
  "Green Mint -Pudina-": "สะระแหน่",
  "Green Peas": "ถั่วเขียว",
  "Green Soyabean -Hariyo Bhatmas-": "ถั่วเหลือง",
  Gundruk: "ผักดอง",
  Ham: "แฮม",
  Ice: "น้ำแข็ง",
  "Jack Fruit": "ขนุน",
  Ketchup: "ซอสมะเขือเทศ",
  "Lapsi -Nepali Hog Plum-": "มะปราง",
  "Lemon -Nimbu-": "มะนาว",
  "Lime -Kagati-": "มะนาว",
  "Long Beans -Bodi-": "ถั่วฝักยาว",
  Masyaura: "ลูกชิ้นถั่ว",
  Milk: "นม",
  "Minced Meat": "เนื้อสับ",
  "Moringa Leaves -Sajyun ko Munta-": "ใบมะรุม",
  Mushroom: "เห็ด",
  Mutton: "เนื้อแพะ",
  "Nutrela -Soya Chunks-": "เต้าหู้ทอด",
  "Okra -Bhindi-": "กระเจี๊ยบ",
  "Olive Oil": "น้ำมันมะกอก",
  Onion: "หัวหอม",
  "Onion Leaves": "ต้นหอม",
  Orange: "ส้ม",
  "Palak -Indian Spinach-": "ผักโขม",
  "Palungo -Nepali Spinach-": "ผักโขม",
  Paneer: "เพนีร์",
  Papaya: "มะละกอ",
  Pea: "ถั่ว",
  Pear: "ลูกแพร์",
  "Pointed Gourd -Chuche Karela-": "มะเขือ",
  Pork: "หมู",
  Potato: "มันฝรั่ง",
  "Pumpkin -Farsi-": "ฟักทอง",
  Radish: "หัวไชเท้า",
  "Rahar ko Daal": "ถั่วแดง",
  "Rayo ko Saag": "ผักกาด",
  "Red Beans": "ถั่วแดง",
  "Red Lentils": "ถั่วแดง",
  "Rice -Chamal-": "ข้าว",
  "Sajjyun -Moringa Drumsticks-": "มะรุม",
  Salt: "เกลือ",
  Sausage: "ไส้กรอก",
  "Snake Gourd -Chichindo-": "บวบ",
  "Soy Sauce": "ซีอิ๊ว",
  "Soyabean -Bhatmas-": "ถั่วเหลือง",
  "Sponge Gourd -Ghiraula-": "บวบ",
  "Stinging Nettle -Sisnu-": "ตำแย",
  Strawberry: "สตรอว์เบอร์รี่",
  Sugar: "น้ำตาล",
  "Sweet Potato -Suthuni-": "มันเทศ",
  "Taro Leaves -Karkalo-": "ใบเผือก",
  "Taro Root-Pidalu-": "เผือก",
  "Thukpa Noodles": "บะหมี่",
  Tofu: "เต้าหู้",
  Tomato: "มะเขือเทศ",
  "Tori ko Saag": "ผักกาด",
  "Tree Tomato -Rukh Tamatar-": "มะเขือเทศ",
  Turnip: "เทอร์นิป",
  Wallnut: "วอลนัท",
  "Water Melon": "แตงโม",
  Wheat: "ข้าวสาลี",
  "Yellow Lentils": "ถั่วเหลือง",
  kimchi: "กิมจิ",
  mayonnaise: "มายองเนส",
  noodle: "เส้นก๋วยเตี๋ยว",
  seaweed: "สาหร่าย",
};

export function toThaiLabel(englishLabel: string): string {
  return labelThMap[englishLabel] ?? englishLabel;
}
